version: '3.8'

volumes:
  database:


services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=graduation
