version: '3.8'

volumes:
  database:


services:
  api:
    build: 
      context: ./api
      dockerfile: ./Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE__HOST=database
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=graduation
