version: '3.9'

networks:
  graduation:


services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
       - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
    command: yarn dev
    ports:
      - 3001:3001
      - 5555:5555
    depends_on:
      - redis
      - database
    networks:
      - graduation

  redis:
    container_name: graduation_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - graduation

  redis-admin:
    container_name: graduation_redis_admin
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - graduation

  database:
    image: postgres
    container_name: graduation_database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - graduation
    expose:
      - 5432

  database_admin:
    image: dpage/pgadmin4
    restart: always
    container_name: graduation_database_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - database-admin:/var/lib/pgadmin
    links:
      - database
    networks:
      - graduation


volumes:
  redis:
    driver: local
  database:
  database-admin: