version: '3.8'

services:
  proxy:
    image: nginx:mainline

  web:
    build:
      context: ./web
      dockerfile: Dockerfile

    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ./src/Api/Dockerfile
      
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: always
