/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as layoutsUserImport } from './routes/(layouts)/_user'
import { Route as layoutsAdminImport } from './routes/(layouts)/_admin'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects/$projectId/index'

// Create Virtual Routes

const homeIndexLazyImport = createFileRoute('/(home)/')()

// Create/Update Routes

const homeIndexLazyRoute = homeIndexLazyImport
  .update({
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy').then((d) => d.Route))

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/index.lazy').then((d) => d.Route),
)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const layoutsUserRoute = layoutsUserImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const layoutsAdminRoute = layoutsAdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/$projectId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(layouts)/_admin': {
      preLoaderRoute: typeof layoutsAdminImport
      parentRoute: typeof rootRoute
    }
    '/(layouts)/_user': {
      preLoaderRoute: typeof layoutsUserImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(home)/': {
      preLoaderRoute: typeof homeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/': {
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  layoutsAdminRoute,
  layoutsUserRoute,
  AuthIndexRoute,
  ProjectsIndexRoute,
  homeIndexLazyRoute,
  ProjectsProjectIdIndexRoute,
])

/* prettier-ignore-end */
